import admin from "firebase-admin";
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const serviceAccount = require("./serviceAccountKey.json");

admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
});

const db = admin.firestore();

// ============================================================
//  DATASET 1 — Agriculture Crop Data
//  Collection: maharashtra_agriculture
// ============================================================

const agricultureData = [
    // ── AMRAVATI DIVISION ──────────────────────────────────────

    // Amravati District
    { district: "Amravati", division: "Amravati", year: 2018, season: "Kharif", crop: "Cotton", area_sown_hectares: 108000, production_tonnes: 151200, yield_kg_per_hectare: 1400, msp_per_quintal_inr: 5150, budget_allocated_lakhs: 38200, budget_utilized_lakhs: 26364, utilization_percent: 69.0, irrigation_coverage_percent: 28, rainfall_mm: 824, farmer_count: 86400, soil_type: "Black" },
    { district: "Amravati", division: "Amravati", year: 2018, season: "Kharif", crop: "Soybean", area_sown_hectares: 88000, production_tonnes: 97680, yield_kg_per_hectare: 1110, msp_per_quintal_inr: 3399, budget_allocated_lakhs: 31200, budget_utilized_lakhs: 21528, utilization_percent: 69.0, irrigation_coverage_percent: 22, rainfall_mm: 824, farmer_count: 70400, soil_type: "Black" },
    { district: "Amravati", division: "Amravati", year: 2019, season: "Kharif", crop: "Cotton", area_sown_hectares: 112000, production_tonnes: 156800, yield_kg_per_hectare: 1400, msp_per_quintal_inr: 5255, budget_allocated_lakhs: 39800, budget_utilized_lakhs: 27462, utilization_percent: 69.0, irrigation_coverage_percent: 29, rainfall_mm: 798, farmer_count: 89600, soil_type: "Black" },
    { district: "Amravati", division: "Amravati", year: 2019, season: "Kharif", crop: "Soybean", area_sown_hectares: 92000, production_tonnes: 103040, yield_kg_per_hectare: 1120, msp_per_quintal_inr: 3710, budget_allocated_lakhs: 32800, budget_utilized_lakhs: 22632, utilization_percent: 69.0, irrigation_coverage_percent: 23, rainfall_mm: 798, farmer_count: 73600, soil_type: "Black" },
    { district: "Amravati", division: "Amravati", year: 2020, season: "Kharif", crop: "Cotton", area_sown_hectares: 116000, production_tonnes: 162400, yield_kg_per_hectare: 1400, msp_per_quintal_inr: 5515, budget_allocated_lakhs: 41500, budget_utilized_lakhs: 28635, utilization_percent: 69.0, irrigation_coverage_percent: 30, rainfall_mm: 912, farmer_count: 92800, soil_type: "Black" },
    { district: "Amravati", division: "Amravati", year: 2020, season: "Kharif", crop: "Soybean", area_sown_hectares: 95000, production_tonnes: 107350, yield_kg_per_hectare: 1130, msp_per_quintal_inr: 3880, budget_allocated_lakhs: 34100, budget_utilized_lakhs: 23529, utilization_percent: 69.0, irrigation_coverage_percent: 24, rainfall_mm: 912, farmer_count: 76000, soil_type: "Black" },
    { district: "Amravati", division: "Amravati", year: 2021, season: "Kharif", crop: "Cotton", area_sown_hectares: 120000, production_tonnes: 172800, yield_kg_per_hectare: 1440, msp_per_quintal_inr: 5726, budget_allocated_lakhs: 43200, budget_utilized_lakhs: 29808, utilization_percent: 69.0, irrigation_coverage_percent: 31, rainfall_mm: 868, farmer_count: 96000, soil_type: "Black" },
    { district: "Amravati", division: "Amravati", year: 2021, season: "Kharif", crop: "Soybean", area_sown_hectares: 98000, production_tonnes: 112700, yield_kg_per_hectare: 1150, msp_per_quintal_inr: 3950, budget_allocated_lakhs: 35600, budget_utilized_lakhs: 24564, utilization_percent: 69.0, irrigation_coverage_percent: 25, rainfall_mm: 868, farmer_count: 78400, soil_type: "Black" },
    { district: "Amravati", division: "Amravati", year: 2022, season: "Kharif", crop: "Cotton", area_sown_hectares: 124000, production_tonnes: 186000, yield_kg_per_hectare: 1500, msp_per_quintal_inr: 6025, budget_allocated_lakhs: 45800, budget_utilized_lakhs: 32060, utilization_percent: 70.0, irrigation_coverage_percent: 32, rainfall_mm: 848, farmer_count: 99200, soil_type: "Black" },
    { district: "Amravati", division: "Amravati", year: 2022, season: "Kharif", crop: "Soybean", area_sown_hectares: 101000, production_tonnes: 120190, yield_kg_per_hectare: 1190, msp_per_quintal_inr: 4300, budget_allocated_lakhs: 37800, budget_utilized_lakhs: 26460, utilization_percent: 70.0, irrigation_coverage_percent: 27, rainfall_mm: 848, farmer_count: 80800, soil_type: "Black" },
    { district: "Amravati", division: "Amravati", year: 2023, season: "Kharif", crop: "Cotton", area_sown_hectares: 130000, production_tonnes: 208000, yield_kg_per_hectare: 1600, msp_per_quintal_inr: 6620, budget_allocated_lakhs: 50200, budget_utilized_lakhs: 40160, utilization_percent: 80.0, irrigation_coverage_percent: 35, rainfall_mm: 862, farmer_count: 104000, soil_type: "Black" },
    { district: "Amravati", division: "Amravati", year: 2023, season: "Kharif", crop: "Soybean", area_sown_hectares: 103000, production_tonnes: 123600, yield_kg_per_hectare: 1200, msp_per_quintal_inr: 4600, budget_allocated_lakhs: 39900, budget_utilized_lakhs: 30324, utilization_percent: 76.0, irrigation_coverage_percent: 28, rainfall_mm: 862, farmer_count: 82400, soil_type: "Black" },
    { district: "Amravati", division: "Amravati", year: 2024, season: "Kharif", crop: "Cotton", area_sown_hectares: 135000, production_tonnes: 220275, yield_kg_per_hectare: 1631, msp_per_quintal_inr: 7020, budget_allocated_lakhs: 53100, budget_utilized_lakhs: 42480, utilization_percent: 80.0, irrigation_coverage_percent: 37, rainfall_mm: 842, farmer_count: 108000, soil_type: "Black" },
    { district: "Amravati", division: "Amravati", year: 2024, season: "Kharif", crop: "Soybean", area_sown_hectares: 108000, production_tonnes: 135000, yield_kg_per_hectare: 1250, msp_per_quintal_inr: 4892, budget_allocated_lakhs: 42200, budget_utilized_lakhs: 33760, utilization_percent: 80.0, irrigation_coverage_percent: 30, rainfall_mm: 842, farmer_count: 86400, soil_type: "Black" },
    { district: "Amravati", division: "Amravati", year: 2025, season: "Kharif", crop: "Cotton", area_sown_hectares: 140000, production_tonnes: 234080, yield_kg_per_hectare: 1672, msp_per_quintal_inr: 7400, budget_allocated_lakhs: 56200, budget_utilized_lakhs: 44960, utilization_percent: 80.0, irrigation_coverage_percent: 39, rainfall_mm: 882, farmer_count: 112000, soil_type: "Black" },
    { district: "Amravati", division: "Amravati", year: 2025, season: "Kharif", crop: "Soybean", area_sown_hectares: 112000, production_tonnes: 141120, yield_kg_per_hectare: 1260, msp_per_quintal_inr: 5100, budget_allocated_lakhs: 44600, budget_utilized_lakhs: 35680, utilization_percent: 80.0, irrigation_coverage_percent: 32, rainfall_mm: 882, farmer_count: 89600, soil_type: "Black" },

    // Akola District
    { district: "Akola", division: "Amravati", year: 2018, season: "Kharif", crop: "Cotton", area_sown_hectares: 86000, production_tonnes: 120400, yield_kg_per_hectare: 1400, msp_per_quintal_inr: 5150, budget_allocated_lakhs: 33200, budget_utilized_lakhs: 22908, utilization_percent: 69.0, irrigation_coverage_percent: 26, rainfall_mm: 742, farmer_count: 68800, soil_type: "Black" },
    { district: "Akola", division: "Amravati", year: 2019, season: "Kharif", crop: "Cotton", area_sown_hectares: 89000, production_tonnes: 124600, yield_kg_per_hectare: 1400, msp_per_quintal_inr: 5255, budget_allocated_lakhs: 34500, budget_utilized_lakhs: 23805, utilization_percent: 69.0, irrigation_coverage_percent: 27, rainfall_mm: 722, farmer_count: 71200, soil_type: "Black" },
    { district: "Akola", division: "Amravati", year: 2020, season: "Kharif", crop: "Cotton", area_sown_hectares: 92000, production_tonnes: 130640, yield_kg_per_hectare: 1420, msp_per_quintal_inr: 5515, budget_allocated_lakhs: 35900, budget_utilized_lakhs: 24771, utilization_percent: 69.0, irrigation_coverage_percent: 28, rainfall_mm: 828, farmer_count: 73600, soil_type: "Black" },
    { district: "Akola", division: "Amravati", year: 2021, season: "Kharif", crop: "Cotton", area_sown_hectares: 95000, production_tonnes: 137750, yield_kg_per_hectare: 1450, msp_per_quintal_inr: 5726, budget_allocated_lakhs: 37200, budget_utilized_lakhs: 25668, utilization_percent: 69.0, irrigation_coverage_percent: 29, rainfall_mm: 788, farmer_count: 76000, soil_type: "Black" },
    { district: "Akola", division: "Amravati", year: 2022, season: "Kharif", crop: "Cotton", area_sown_hectares: 99000, production_tonnes: 148500, yield_kg_per_hectare: 1500, msp_per_quintal_inr: 6025, budget_allocated_lakhs: 39200, budget_utilized_lakhs: 27440, utilization_percent: 70.0, irrigation_coverage_percent: 30, rainfall_mm: 768, farmer_count: 79200, soil_type: "Black" },
    { district: "Akola", division: "Amravati", year: 2023, season: "Kharif", crop: "Cotton", area_sown_hectares: 103000, production_tonnes: 164800, yield_kg_per_hectare: 1600, msp_per_quintal_inr: 6620, budget_allocated_lakhs: 41500, budget_utilized_lakhs: 28635, utilization_percent: 69.0, irrigation_coverage_percent: 32, rainfall_mm: 762, farmer_count: 82400, soil_type: "Black" },
    { district: "Akola", division: "Amravati", year: 2024, season: "Kharif", crop: "Cotton", area_sown_hectares: 108000, production_tonnes: 172800, yield_kg_per_hectare: 1600, msp_per_quintal_inr: 7020, budget_allocated_lakhs: 43800, budget_utilized_lakhs: 30660, utilization_percent: 70.0, irrigation_coverage_percent: 34, rainfall_mm: 742, farmer_count: 86400, soil_type: "Black" },
    { district: "Akola", division: "Amravati", year: 2025, season: "Kharif", crop: "Cotton", area_sown_hectares: 112000, production_tonnes: 184288, yield_kg_per_hectare: 1645, msp_per_quintal_inr: 7400, budget_allocated_lakhs: 46200, budget_utilized_lakhs: 36960, utilization_percent: 80.0, irrigation_coverage_percent: 36, rainfall_mm: 782, farmer_count: 89600, soil_type: "Black" },

    // Yavatmal District
    { district: "Yavatmal", division: "Amravati", year: 2018, season: "Kharif", crop: "Cotton", area_sown_hectares: 128000, production_tonnes: 179200, yield_kg_per_hectare: 1400, msp_per_quintal_inr: 5150, budget_allocated_lakhs: 48600, budget_utilized_lakhs: 33534, utilization_percent: 69.0, irrigation_coverage_percent: 26, rainfall_mm: 848, farmer_count: 102400, soil_type: "Black" },
    { district: "Yavatmal", division: "Amravati", year: 2019, season: "Kharif", crop: "Cotton", area_sown_hectares: 133000, production_tonnes: 186200, yield_kg_per_hectare: 1400, msp_per_quintal_inr: 5255, budget_allocated_lakhs: 50400, budget_utilized_lakhs: 34776, utilization_percent: 69.0, irrigation_coverage_percent: 27, rainfall_mm: 828, farmer_count: 106400, soil_type: "Black" },
    { district: "Yavatmal", division: "Amravati", year: 2020, season: "Kharif", crop: "Cotton", area_sown_hectares: 137000, production_tonnes: 197280, yield_kg_per_hectare: 1440, msp_per_quintal_inr: 5515, budget_allocated_lakhs: 52300, budget_utilized_lakhs: 36092, utilization_percent: 69.0, irrigation_coverage_percent: 28, rainfall_mm: 948, farmer_count: 109600, soil_type: "Black" },
    { district: "Yavatmal", division: "Amravati", year: 2021, season: "Kharif", crop: "Cotton", area_sown_hectares: 141000, production_tonnes: 208680, yield_kg_per_hectare: 1480, msp_per_quintal_inr: 5726, budget_allocated_lakhs: 54200, budget_utilized_lakhs: 37398, utilization_percent: 69.0, irrigation_coverage_percent: 29, rainfall_mm: 898, farmer_count: 112800, soil_type: "Black" },
    { district: "Yavatmal", division: "Amravati", year: 2022, season: "Kharif", crop: "Cotton", area_sown_hectares: 145000, production_tonnes: 217500, yield_kg_per_hectare: 1500, msp_per_quintal_inr: 6025, budget_allocated_lakhs: 56400, budget_utilized_lakhs: 39480, utilization_percent: 70.0, irrigation_coverage_percent: 30, rainfall_mm: 878, farmer_count: 116000, soil_type: "Black" },
    { district: "Yavatmal", division: "Amravati", year: 2023, season: "Kharif", crop: "Cotton", area_sown_hectares: 149000, production_tonnes: 238400, yield_kg_per_hectare: 1600, msp_per_quintal_inr: 6620, budget_allocated_lakhs: 59100, budget_utilized_lakhs: 41370, utilization_percent: 70.0, irrigation_coverage_percent: 32, rainfall_mm: 888, farmer_count: 119200, soil_type: "Black" },
    { district: "Yavatmal", division: "Amravati", year: 2024, season: "Kharif", crop: "Cotton", area_sown_hectares: 154000, production_tonnes: 254100, yield_kg_per_hectare: 1650, msp_per_quintal_inr: 7020, budget_allocated_lakhs: 62300, budget_utilized_lakhs: 43610, utilization_percent: 70.0, irrigation_coverage_percent: 34, rainfall_mm: 868, farmer_count: 123200, soil_type: "Black" },
    { district: "Yavatmal", division: "Amravati", year: 2025, season: "Kharif", crop: "Cotton", area_sown_hectares: 159000, production_tonnes: 268710, yield_kg_per_hectare: 1690, msp_per_quintal_inr: 7400, budget_allocated_lakhs: 65800, budget_utilized_lakhs: 52640, utilization_percent: 80.0, irrigation_coverage_percent: 36, rainfall_mm: 908, farmer_count: 127200, soil_type: "Black" },

    // Nagpur District
    { district: "Nagpur", division: "Nagpur", year: 2018, season: "Kharif", crop: "Orange", area_sown_hectares: 30000, production_tonnes: 450000, yield_kg_per_hectare: 15000, msp_per_quintal_inr: 3000, budget_allocated_lakhs: 36800, budget_utilized_lakhs: 33120, utilization_percent: 90.0, irrigation_coverage_percent: 48, rainfall_mm: 964, farmer_count: 24000, soil_type: "Red Laterite" },
    { district: "Nagpur", division: "Nagpur", year: 2019, season: "Kharif", crop: "Orange", area_sown_hectares: 32000, production_tonnes: 480000, yield_kg_per_hectare: 15000, msp_per_quintal_inr: 3100, budget_allocated_lakhs: 38500, budget_utilized_lakhs: 34650, utilization_percent: 90.0, irrigation_coverage_percent: 50, rainfall_mm: 938, farmer_count: 25600, soil_type: "Red Laterite" },
    { district: "Nagpur", division: "Nagpur", year: 2020, season: "Kharif", crop: "Orange", area_sown_hectares: 34000, production_tonnes: 518800, yield_kg_per_hectare: 15259, msp_per_quintal_inr: 3200, budget_allocated_lakhs: 40400, budget_utilized_lakhs: 36360, utilization_percent: 90.0, irrigation_coverage_percent: 51, rainfall_mm: 1048, farmer_count: 27200, soil_type: "Red Laterite" },
    { district: "Nagpur", division: "Nagpur", year: 2021, season: "Kharif", crop: "Orange", area_sown_hectares: 36000, production_tonnes: 550800, yield_kg_per_hectare: 15300, msp_per_quintal_inr: 3300, budget_allocated_lakhs: 42400, budget_utilized_lakhs: 38160, utilization_percent: 90.0, irrigation_coverage_percent: 52, rainfall_mm: 998, farmer_count: 28800, soil_type: "Red Laterite" },
    { district: "Nagpur", division: "Nagpur", year: 2022, season: "Kharif", crop: "Orange", area_sown_hectares: 38000, production_tonnes: 589300, yield_kg_per_hectare: 15508, msp_per_quintal_inr: 3400, budget_allocated_lakhs: 44500, budget_utilized_lakhs: 40050, utilization_percent: 90.0, irrigation_coverage_percent: 50, rainfall_mm: 988, farmer_count: 30400, soil_type: "Red Laterite" },
    { district: "Nagpur", division: "Nagpur", year: 2023, season: "Kharif", crop: "Orange", area_sown_hectares: 40000, production_tonnes: 648000, yield_kg_per_hectare: 16200, msp_per_quintal_inr: 3800, budget_allocated_lakhs: 45800, budget_utilized_lakhs: 41220, utilization_percent: 90.0, irrigation_coverage_percent: 52, rainfall_mm: 1024, farmer_count: 32000, soil_type: "Red Laterite" },
    { district: "Nagpur", division: "Nagpur", year: 2024, season: "Kharif", crop: "Orange", area_sown_hectares: 42000, production_tonnes: 688800, yield_kg_per_hectare: 16400, msp_per_quintal_inr: 3900, budget_allocated_lakhs: 48400, budget_utilized_lakhs: 43560, utilization_percent: 90.0, irrigation_coverage_percent: 54, rainfall_mm: 1008, farmer_count: 33600, soil_type: "Red Laterite" },
    { district: "Nagpur", division: "Nagpur", year: 2025, season: "Kharif", crop: "Orange", area_sown_hectares: 44000, production_tonnes: 731600, yield_kg_per_hectare: 16627, msp_per_quintal_inr: 4000, budget_allocated_lakhs: 51200, budget_utilized_lakhs: 40960, utilization_percent: 80.0, irrigation_coverage_percent: 56, rainfall_mm: 1042, farmer_count: 35200, soil_type: "Red Laterite" },

    // Chandrapur District
    { district: "Chandrapur", division: "Nagpur", year: 2018, season: "Kharif", crop: "Rice", area_sown_hectares: 80000, production_tonnes: 136000, yield_kg_per_hectare: 1700, msp_per_quintal_inr: 1750, budget_allocated_lakhs: 31400, budget_utilized_lakhs: 27632, utilization_percent: 88.0, irrigation_coverage_percent: 56, rainfall_mm: 1372, farmer_count: 64000, soil_type: "Red Sandy" },
    { district: "Chandrapur", division: "Nagpur", year: 2019, season: "Kharif", crop: "Rice", area_sown_hectares: 83000, production_tonnes: 143590, yield_kg_per_hectare: 1730, msp_per_quintal_inr: 1815, budget_allocated_lakhs: 32800, budget_utilized_lakhs: 28864, utilization_percent: 88.0, irrigation_coverage_percent: 58, rainfall_mm: 1342, farmer_count: 66400, soil_type: "Red Sandy" },
    { district: "Chandrapur", division: "Nagpur", year: 2020, season: "Kharif", crop: "Rice", area_sown_hectares: 86000, production_tonnes: 150500, yield_kg_per_hectare: 1750, msp_per_quintal_inr: 1868, budget_allocated_lakhs: 34100, budget_utilized_lakhs: 30008, utilization_percent: 88.0, irrigation_coverage_percent: 59, rainfall_mm: 1468, farmer_count: 68800, soil_type: "Red Sandy" },
    { district: "Chandrapur", division: "Nagpur", year: 2021, season: "Kharif", crop: "Rice", area_sown_hectares: 89000, production_tonnes: 158920, yield_kg_per_hectare: 1786, msp_per_quintal_inr: 1868, budget_allocated_lakhs: 35400, budget_utilized_lakhs: 31152, utilization_percent: 88.0, irrigation_coverage_percent: 60, rainfall_mm: 1408, farmer_count: 71200, soil_type: "Red Sandy" },
    { district: "Chandrapur", division: "Nagpur", year: 2022, season: "Kharif", crop: "Rice", area_sown_hectares: 92000, production_tonnes: 166760, yield_kg_per_hectare: 1813, msp_per_quintal_inr: 2015, budget_allocated_lakhs: 36900, budget_utilized_lakhs: 32472, utilization_percent: 88.0, irrigation_coverage_percent: 61, rainfall_mm: 1398, farmer_count: 73600, soil_type: "Red Sandy" },
    { district: "Chandrapur", division: "Nagpur", year: 2023, season: "Kharif", crop: "Rice", area_sown_hectares: 96000, production_tonnes: 175680, yield_kg_per_hectare: 1830, msp_per_quintal_inr: 2183, budget_allocated_lakhs: 38800, budget_utilized_lakhs: 34144, utilization_percent: 88.0, irrigation_coverage_percent: 62, rainfall_mm: 1412, farmer_count: 76800, soil_type: "Red Sandy" },
    { district: "Chandrapur", division: "Nagpur", year: 2024, season: "Kharif", crop: "Rice", area_sown_hectares: 100000, production_tonnes: 184000, yield_kg_per_hectare: 1840, msp_per_quintal_inr: 2183, budget_allocated_lakhs: 40900, budget_utilized_lakhs: 36000, utilization_percent: 88.0, irrigation_coverage_percent: 64, rainfall_mm: 1388, farmer_count: 80000, soil_type: "Red Sandy" },
    { district: "Chandrapur", division: "Nagpur", year: 2025, season: "Kharif", crop: "Rice", area_sown_hectares: 104000, production_tonnes: 195520, yield_kg_per_hectare: 1880, msp_per_quintal_inr: 2300, budget_allocated_lakhs: 43200, budget_utilized_lakhs: 34560, utilization_percent: 80.0, irrigation_coverage_percent: 66, rainfall_mm: 1438, farmer_count: 83200, soil_type: "Red Sandy" },

    // Aurangabad District
    { district: "Aurangabad", division: "Aurangabad", year: 2018, season: "Kharif", crop: "Cotton", area_sown_hectares: 66000, production_tonnes: 92400, yield_kg_per_hectare: 1400, msp_per_quintal_inr: 5150, budget_allocated_lakhs: 27200, budget_utilized_lakhs: 19584, utilization_percent: 72.0, irrigation_coverage_percent: 28, rainfall_mm: 718, farmer_count: 52800, soil_type: "Black" },
    { district: "Aurangabad", division: "Aurangabad", year: 2018, season: "Kharif", crop: "Soybean", area_sown_hectares: 82000, production_tonnes: 91020, yield_kg_per_hectare: 1110, msp_per_quintal_inr: 3399, budget_allocated_lakhs: 32100, budget_utilized_lakhs: 22470, utilization_percent: 70.0, irrigation_coverage_percent: 22, rainfall_mm: 718, farmer_count: 65600, soil_type: "Black" },
    { district: "Aurangabad", division: "Aurangabad", year: 2019, season: "Kharif", crop: "Cotton", area_sown_hectares: 69000, production_tonnes: 96600, yield_kg_per_hectare: 1400, msp_per_quintal_inr: 5255, budget_allocated_lakhs: 28400, budget_utilized_lakhs: 20448, utilization_percent: 72.0, irrigation_coverage_percent: 29, rainfall_mm: 694, farmer_count: 55200, soil_type: "Black" },
    { district: "Aurangabad", division: "Aurangabad", year: 2020, season: "Kharif", crop: "Cotton", area_sown_hectares: 72000, production_tonnes: 103680, yield_kg_per_hectare: 1440, msp_per_quintal_inr: 5515, budget_allocated_lakhs: 29700, budget_utilized_lakhs: 21384, utilization_percent: 72.0, irrigation_coverage_percent: 30, rainfall_mm: 818, farmer_count: 57600, soil_type: "Black" },
    { district: "Aurangabad", division: "Aurangabad", year: 2021, season: "Kharif", crop: "Cotton", area_sown_hectares: 75000, production_tonnes: 112500, yield_kg_per_hectare: 1500, msp_per_quintal_inr: 5726, budget_allocated_lakhs: 31100, budget_utilized_lakhs: 22392, utilization_percent: 72.0, irrigation_coverage_percent: 31, rainfall_mm: 778, farmer_count: 60000, soil_type: "Black" },
    { district: "Aurangabad", division: "Aurangabad", year: 2022, season: "Kharif", crop: "Cotton", area_sown_hectares: 78000, production_tonnes: 120900, yield_kg_per_hectare: 1550, msp_per_quintal_inr: 6025, budget_allocated_lakhs: 32600, budget_utilized_lakhs: 23472, utilization_percent: 72.0, irrigation_coverage_percent: 32, rainfall_mm: 758, farmer_count: 62400, soil_type: "Black" },
    { district: "Aurangabad", division: "Aurangabad", year: 2023, season: "Kharif", crop: "Cotton", area_sown_hectares: 82000, production_tonnes: 128920, yield_kg_per_hectare: 1572, msp_per_quintal_inr: 6620, budget_allocated_lakhs: 34300, budget_utilized_lakhs: 24696, utilization_percent: 72.0, irrigation_coverage_percent: 34, rainfall_mm: 748, farmer_count: 65600, soil_type: "Black" },
    { district: "Aurangabad", division: "Aurangabad", year: 2024, season: "Kharif", crop: "Cotton", area_sown_hectares: 86000, production_tonnes: 143100, yield_kg_per_hectare: 1664, msp_per_quintal_inr: 7020, budget_allocated_lakhs: 36200, budget_utilized_lakhs: 26064, utilization_percent: 72.0, irrigation_coverage_percent: 36, rainfall_mm: 728, farmer_count: 68800, soil_type: "Black" },
    { district: "Aurangabad", division: "Aurangabad", year: 2025, season: "Kharif", crop: "Cotton", area_sown_hectares: 90000, production_tonnes: 152100, yield_kg_per_hectare: 1690, msp_per_quintal_inr: 7400, budget_allocated_lakhs: 38300, budget_utilized_lakhs: 30640, utilization_percent: 80.0, irrigation_coverage_percent: 38, rainfall_mm: 762, farmer_count: 72000, soil_type: "Black" },

    // Latur District
    { district: "Latur", division: "Aurangabad", year: 2018, season: "Kharif", crop: "Soybean", area_sown_hectares: 104000, production_tonnes: 115440, yield_kg_per_hectare: 1110, msp_per_quintal_inr: 3399, budget_allocated_lakhs: 40200, budget_utilized_lakhs: 28140, utilization_percent: 70.0, irrigation_coverage_percent: 20, rainfall_mm: 672, farmer_count: 83200, soil_type: "Black" },
    { district: "Latur", division: "Aurangabad", year: 2019, season: "Kharif", crop: "Soybean", area_sown_hectares: 108000, production_tonnes: 120960, yield_kg_per_hectare: 1120, msp_per_quintal_inr: 3710, budget_allocated_lakhs: 42000, budget_utilized_lakhs: 29400, utilization_percent: 70.0, irrigation_coverage_percent: 21, rainfall_mm: 648, farmer_count: 86400, soil_type: "Black" },
    { district: "Latur", division: "Aurangabad", year: 2020, season: "Kharif", crop: "Soybean", area_sown_hectares: 112000, production_tonnes: 128800, yield_kg_per_hectare: 1150, msp_per_quintal_inr: 3880, budget_allocated_lakhs: 43900, budget_utilized_lakhs: 30730, utilization_percent: 70.0, irrigation_coverage_percent: 22, rainfall_mm: 788, farmer_count: 89600, soil_type: "Black" },
    { district: "Latur", division: "Aurangabad", year: 2021, season: "Kharif", crop: "Soybean", area_sown_hectares: 116000, production_tonnes: 135720, yield_kg_per_hectare: 1170, msp_per_quintal_inr: 3950, budget_allocated_lakhs: 45800, budget_utilized_lakhs: 32060, utilization_percent: 70.0, irrigation_coverage_percent: 23, rainfall_mm: 728, farmer_count: 92800, soil_type: "Black" },
    { district: "Latur", division: "Aurangabad", year: 2022, season: "Kharif", crop: "Soybean", area_sown_hectares: 120000, production_tonnes: 144000, yield_kg_per_hectare: 1200, msp_per_quintal_inr: 4300, budget_allocated_lakhs: 47900, budget_utilized_lakhs: 33530, utilization_percent: 70.0, irrigation_coverage_percent: 24, rainfall_mm: 708, farmer_count: 96000, soil_type: "Black" },
    { district: "Latur", division: "Aurangabad", year: 2023, season: "Kharif", crop: "Soybean", area_sown_hectares: 124000, production_tonnes: 148800, yield_kg_per_hectare: 1200, msp_per_quintal_inr: 4600, budget_allocated_lakhs: 50400, budget_utilized_lakhs: 35280, utilization_percent: 70.0, irrigation_coverage_percent: 25, rainfall_mm: 712, farmer_count: 99200, soil_type: "Black" },
    { district: "Latur", division: "Aurangabad", year: 2024, season: "Kharif", crop: "Soybean", area_sown_hectares: 129000, production_tonnes: 154800, yield_kg_per_hectare: 1200, msp_per_quintal_inr: 4892, budget_allocated_lakhs: 53300, budget_utilized_lakhs: 37310, utilization_percent: 70.0, irrigation_coverage_percent: 26, rainfall_mm: 692, farmer_count: 103200, soil_type: "Black" },
    { district: "Latur", division: "Aurangabad", year: 2025, season: "Kharif", crop: "Soybean", area_sown_hectares: 134000, production_tonnes: 168210, yield_kg_per_hectare: 1256, msp_per_quintal_inr: 5100, budget_allocated_lakhs: 56500, budget_utilized_lakhs: 45200, utilization_percent: 80.0, irrigation_coverage_percent: 27, rainfall_mm: 724, farmer_count: 107200, soil_type: "Black" },

    // Nanded District
    { district: "Nanded", division: "Aurangabad", year: 2018, season: "Kharif", crop: "Soybean", area_sown_hectares: 96000, production_tonnes: 106560, yield_kg_per_hectare: 1110, msp_per_quintal_inr: 3399, budget_allocated_lakhs: 37200, budget_utilized_lakhs: 26040, utilization_percent: 70.0, irrigation_coverage_percent: 22, rainfall_mm: 722, farmer_count: 76800, soil_type: "Black" },
    { district: "Nanded", division: "Aurangabad", year: 2019, season: "Kharif", crop: "Soybean", area_sown_hectares: 100000, production_tonnes: 112000, yield_kg_per_hectare: 1120, msp_per_quintal_inr: 3710, budget_allocated_lakhs: 38800, budget_utilized_lakhs: 27160, utilization_percent: 70.0, irrigation_coverage_percent: 23, rainfall_mm: 702, farmer_count: 80000, soil_type: "Black" },
    { district: "Nanded", division: "Aurangabad", year: 2020, season: "Kharif", crop: "Soybean", area_sown_hectares: 104000, production_tonnes: 119600, yield_kg_per_hectare: 1150, msp_per_quintal_inr: 3880, budget_allocated_lakhs: 40500, budget_utilized_lakhs: 28350, utilization_percent: 70.0, irrigation_coverage_percent: 24, rainfall_mm: 822, farmer_count: 83200, soil_type: "Black" },
    { district: "Nanded", division: "Aurangabad", year: 2021, season: "Kharif", crop: "Soybean", area_sown_hectares: 108000, production_tonnes: 126360, yield_kg_per_hectare: 1170, msp_per_quintal_inr: 3950, budget_allocated_lakhs: 42200, budget_utilized_lakhs: 29540, utilization_percent: 70.0, irrigation_coverage_percent: 25, rainfall_mm: 762, farmer_count: 86400, soil_type: "Black" },
    { district: "Nanded", division: "Aurangabad", year: 2022, season: "Kharif", crop: "Soybean", area_sown_hectares: 112000, production_tonnes: 134400, yield_kg_per_hectare: 1200, msp_per_quintal_inr: 4300, budget_allocated_lakhs: 44100, budget_utilized_lakhs: 30870, utilization_percent: 70.0, irrigation_coverage_percent: 26, rainfall_mm: 742, farmer_count: 89600, soil_type: "Black" },
    { district: "Nanded", division: "Aurangabad", year: 2023, season: "Kharif", crop: "Soybean", area_sown_hectares: 116000, production_tonnes: 139200, yield_kg_per_hectare: 1200, msp_per_quintal_inr: 4600, budget_allocated_lakhs: 46300, budget_utilized_lakhs: 32410, utilization_percent: 70.0, irrigation_coverage_percent: 27, rainfall_mm: 762, farmer_count: 92800, soil_type: "Black" },
    { district: "Nanded", division: "Aurangabad", year: 2024, season: "Kharif", crop: "Soybean", area_sown_hectares: 121000, production_tonnes: 145200, yield_kg_per_hectare: 1200, msp_per_quintal_inr: 4892, budget_allocated_lakhs: 49000, budget_utilized_lakhs: 34300, utilization_percent: 70.0, irrigation_coverage_percent: 28, rainfall_mm: 742, farmer_count: 96800, soil_type: "Black" },
    { district: "Nanded", division: "Aurangabad", year: 2025, season: "Kharif", crop: "Soybean", area_sown_hectares: 126000, production_tonnes: 158760, yield_kg_per_hectare: 1260, msp_per_quintal_inr: 5100, budget_allocated_lakhs: 51900, budget_utilized_lakhs: 41520, utilization_percent: 80.0, irrigation_coverage_percent: 29, rainfall_mm: 778, farmer_count: 100800, soil_type: "Black" },
];

// ============================================================
//  DATASET 2 — Agriculture Finance & Policy Data
//  Collection: maharashtra_agri_finance
// ============================================================

const financeData = [
    // ── AMRAVATI ───────────────────────────────────────────────
    { district: "Amravati", division: "Amravati", year: 2018, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 18200, amount_released_lakhs: 18200, amount_spent_lakhs: 16016, balance_unspent_lakhs: 2184, utilization_percent: 88.0, beneficiary_farmers: 121600, fund_source: "Central Government", remarks: "Scheme launched Dec 2018; partial year" },
    { district: "Amravati", division: "Amravati", year: 2018, scheme_name: "PMFBY (Crop Insurance)", scheme_type: "Crop Insurance", policy_level: "Central-State", budget_sanctioned_lakhs: 24600, amount_released_lakhs: 22140, amount_spent_lakhs: 20048, balance_unspent_lakhs: 2092, utilization_percent: 81.5, beneficiary_farmers: 98200, fund_source: "Central+State (50:50)", remarks: "Kharif 2018 coverage" },
    { district: "Amravati", division: "Amravati", year: 2018, scheme_name: "RKVY (Agri Dev)", scheme_type: "Infrastructure", policy_level: "Central-State", budget_sanctioned_lakhs: 8400, amount_released_lakhs: 7560, amount_spent_lakhs: 6350, balance_unspent_lakhs: 1210, utilization_percent: 75.6, beneficiary_farmers: 0, fund_source: "Central+State (60:40)", remarks: "Rashtriya Krishi Vikas Yojana" },
    { district: "Amravati", division: "Amravati", year: 2018, scheme_name: "PMKSY (Micro Irrigation)", scheme_type: "Irrigation", policy_level: "Central-State", budget_sanctioned_lakhs: 6800, amount_released_lakhs: 5780, amount_spent_lakhs: 4912, balance_unspent_lakhs: 868, utilization_percent: 72.2, beneficiary_farmers: 52000, fund_source: "Central+State (60:40)", remarks: "Drip & sprinkler installation" },
    { district: "Amravati", division: "Amravati", year: 2018, scheme_name: "State Agri Relief Fund", scheme_type: "Drought Relief", policy_level: "State", budget_sanctioned_lakhs: 9200, amount_released_lakhs: 9200, amount_spent_lakhs: 8648, balance_unspent_lakhs: 552, utilization_percent: 94.0, beneficiary_farmers: 72000, fund_source: "State Government", remarks: "Drought relief 2018" },
    { district: "Amravati", division: "Amravati", year: 2019, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 21600, amount_released_lakhs: 21600, amount_spent_lakhs: 20304, balance_unspent_lakhs: 1296, utilization_percent: 94.0, beneficiary_farmers: 144000, fund_source: "Central Government", remarks: "Full year; Rs 6000/farmer/year" },
    { district: "Amravati", division: "Amravati", year: 2019, scheme_name: "PMFBY (Crop Insurance)", scheme_type: "Crop Insurance", policy_level: "Central-State", budget_sanctioned_lakhs: 26400, amount_released_lakhs: 23760, amount_spent_lakhs: 21384, balance_unspent_lakhs: 2376, utilization_percent: 81.0, beneficiary_farmers: 105400, fund_source: "Central+State (50:50)", remarks: "Kharif+Rabi 2019" },
    { district: "Amravati", division: "Amravati", year: 2019, scheme_name: "State Agri Relief Fund", scheme_type: "Flood Relief", policy_level: "State", budget_sanctioned_lakhs: 11400, amount_released_lakhs: 11400, amount_spent_lakhs: 10602, balance_unspent_lakhs: 798, utilization_percent: 93.0, beneficiary_farmers: 88000, fund_source: "State Government", remarks: "Flood relief 2019" },
    { district: "Amravati", division: "Amravati", year: 2020, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 22800, amount_released_lakhs: 22800, amount_spent_lakhs: 21432, balance_unspent_lakhs: 1368, utilization_percent: 94.0, beneficiary_farmers: 152000, fund_source: "Central Government", remarks: "Covid year; payments continued" },
    { district: "Amravati", division: "Amravati", year: 2020, scheme_name: "PMFBY (Crop Insurance)", scheme_type: "Crop Insurance", policy_level: "Central-State", budget_sanctioned_lakhs: 28200, amount_released_lakhs: 25380, amount_spent_lakhs: 22842, balance_unspent_lakhs: 2538, utilization_percent: 81.0, beneficiary_farmers: 112600, fund_source: "Central+State (50:50)", remarks: "Kharif+Rabi 2020" },
    { district: "Amravati", division: "Amravati", year: 2020, scheme_name: "Covid Agri Relief Package", scheme_type: "Special Relief", policy_level: "Central-State", budget_sanctioned_lakhs: 15600, amount_released_lakhs: 15600, amount_spent_lakhs: 14664, balance_unspent_lakhs: 936, utilization_percent: 94.0, beneficiary_farmers: 124800, fund_source: "Central+State", remarks: "Special Covid relief for farmers" },
    { district: "Amravati", division: "Amravati", year: 2020, scheme_name: "AIF (Agri Infrastructure)", scheme_type: "Infrastructure", policy_level: "Central", budget_sanctioned_lakhs: 3200, amount_released_lakhs: 2880, amount_spent_lakhs: 2016, balance_unspent_lakhs: 864, utilization_percent: 63.0, beneficiary_farmers: 0, fund_source: "Central Government", remarks: "AIF launched 2020; initial year" },
    { district: "Amravati", division: "Amravati", year: 2021, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 23400, amount_released_lakhs: 23400, amount_spent_lakhs: 22230, balance_unspent_lakhs: 1170, utilization_percent: 95.0, beneficiary_farmers: 156000, fund_source: "Central Government", remarks: "3 instalments of Rs 2000 each" },
    { district: "Amravati", division: "Amravati", year: 2021, scheme_name: "PMFBY (Crop Insurance)", scheme_type: "Crop Insurance", policy_level: "Central-State", budget_sanctioned_lakhs: 29800, amount_released_lakhs: 26820, amount_spent_lakhs: 24138, balance_unspent_lakhs: 2682, utilization_percent: 81.0, beneficiary_farmers: 119200, fund_source: "Central+State (50:50)", remarks: "Kharif+Rabi 2021" },
    { district: "Amravati", division: "Amravati", year: 2021, scheme_name: "Nanaji Deshmukh Krishi Sanjivani", scheme_type: "Climate Resilience", policy_level: "State-World Bank", budget_sanctioned_lakhs: 12400, amount_released_lakhs: 11160, amount_spent_lakhs: 9928, balance_unspent_lakhs: 1232, utilization_percent: 80.0, beneficiary_farmers: 96000, fund_source: "State+World Bank", remarks: "Climate resilient agri project" },
    { district: "Amravati", division: "Amravati", year: 2022, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 24000, amount_released_lakhs: 24000, amount_spent_lakhs: 22800, balance_unspent_lakhs: 1200, utilization_percent: 95.0, beneficiary_farmers: 160000, fund_source: "Central Government", remarks: "Continued; DBT mode" },
    { district: "Amravati", division: "Amravati", year: 2022, scheme_name: "PMFBY (Crop Insurance)", scheme_type: "Crop Insurance", policy_level: "Central-State", budget_sanctioned_lakhs: 31200, amount_released_lakhs: 28080, amount_spent_lakhs: 25272, balance_unspent_lakhs: 2808, utilization_percent: 81.0, beneficiary_farmers: 124800, fund_source: "Central+State (50:50)", remarks: "Premium enhanced FY22" },
    { district: "Amravati", division: "Amravati", year: 2022, scheme_name: "Nanaji Deshmukh Krishi Sanjivani", scheme_type: "Climate Resilience", policy_level: "State-World Bank", budget_sanctioned_lakhs: 13800, amount_released_lakhs: 12420, amount_spent_lakhs: 11038, balance_unspent_lakhs: 1382, utilization_percent: 80.0, beneficiary_farmers: 107200, fund_source: "State+World Bank", remarks: "Phase 2 villages" },
    { district: "Amravati", division: "Amravati", year: 2023, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 25200, amount_released_lakhs: 25200, amount_spent_lakhs: 23940, balance_unspent_lakhs: 1260, utilization_percent: 95.0, beneficiary_farmers: 168000, fund_source: "Central Government", remarks: "Installment 13-15 released" },
    { district: "Amravati", division: "Amravati", year: 2023, scheme_name: "Namo Shetkari Mahasanman Nidhi", scheme_type: "Direct Income Support", policy_level: "State", budget_sanctioned_lakhs: 10320, amount_released_lakhs: 10320, amount_spent_lakhs: 9804, balance_unspent_lakhs: 516, utilization_percent: 95.0, beneficiary_farmers: 137600, fund_source: "State Government", remarks: "Rs 6000/year additional; launched 2023" },
    { district: "Amravati", division: "Amravati", year: 2023, scheme_name: "PMFBY (Crop Insurance)", scheme_type: "Crop Insurance", policy_level: "Central-State", budget_sanctioned_lakhs: 33600, amount_released_lakhs: 30240, amount_spent_lakhs: 27216, balance_unspent_lakhs: 3024, utilization_percent: 81.0, beneficiary_farmers: 134400, fund_source: "Central+State (50:50)", remarks: "Highest allocation year" },
    { district: "Amravati", division: "Amravati", year: 2023, scheme_name: "PMKSY (Micro Irrigation)", scheme_type: "Irrigation", policy_level: "Central-State", budget_sanctioned_lakhs: 8800, amount_released_lakhs: 7480, amount_spent_lakhs: 6417, balance_unspent_lakhs: 1063, utilization_percent: 73.0, beneficiary_farmers: 68800, fund_source: "Central+State (60:40)", remarks: "Expanded drip network" },
    { district: "Amravati", division: "Amravati", year: 2024, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 26400, amount_released_lakhs: 26400, amount_spent_lakhs: 25080, balance_unspent_lakhs: 1320, utilization_percent: 95.0, beneficiary_farmers: 176000, fund_source: "Central Government", remarks: "Installment 16-18 released" },
    { district: "Amravati", division: "Amravati", year: 2024, scheme_name: "Namo Shetkari Mahasanman Nidhi", scheme_type: "Direct Income Support", policy_level: "State", budget_sanctioned_lakhs: 10800, amount_released_lakhs: 10800, amount_spent_lakhs: 10260, balance_unspent_lakhs: 540, utilization_percent: 95.0, beneficiary_farmers: 144000, fund_source: "State Government", remarks: "5th installment released Oct 2024" },
    { district: "Amravati", division: "Amravati", year: 2024, scheme_name: "PMFBY (Crop Insurance)", scheme_type: "Crop Insurance", policy_level: "Central-State", budget_sanctioned_lakhs: 35200, amount_released_lakhs: 31680, amount_spent_lakhs: 28512, balance_unspent_lakhs: 3168, utilization_percent: 81.0, beneficiary_farmers: 140800, fund_source: "Central+State (50:50)", remarks: "Kharif+Rabi 2024" },
    { district: "Amravati", division: "Amravati", year: 2025, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 27600, amount_released_lakhs: 27600, amount_spent_lakhs: 26220, balance_unspent_lakhs: 1380, utilization_percent: 95.0, beneficiary_farmers: 184000, fund_source: "Central Government", remarks: "Projected FY 2025-26" },
    { district: "Amravati", division: "Amravati", year: 2025, scheme_name: "Namo Shetkari Mahasanman Nidhi", scheme_type: "Direct Income Support", policy_level: "State", budget_sanctioned_lakhs: 11400, amount_released_lakhs: 11400, amount_spent_lakhs: 10830, balance_unspent_lakhs: 570, utilization_percent: 95.0, beneficiary_farmers: 152000, fund_source: "State Government", remarks: "Rs 6900 Cr state budget alloc" },
    { district: "Amravati", division: "Amravati", year: 2025, scheme_name: "PMFBY (Crop Insurance)", scheme_type: "Crop Insurance", policy_level: "Central-State", budget_sanctioned_lakhs: 37200, amount_released_lakhs: 33480, amount_spent_lakhs: 30132, balance_unspent_lakhs: 3348, utilization_percent: 81.0, beneficiary_farmers: 148800, fund_source: "Central+State (50:50)", remarks: "Budget 2025-26 allocation" },

    // ── NAGPUR ────────────────────────────────────────────────
    { district: "Nagpur", division: "Nagpur", year: 2018, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 9600, amount_released_lakhs: 9600, amount_spent_lakhs: 8448, balance_unspent_lakhs: 1152, utilization_percent: 88.0, beneficiary_farmers: 64000, fund_source: "Central Government", remarks: "Launch year" },
    { district: "Nagpur", division: "Nagpur", year: 2018, scheme_name: "PMFBY (Crop Insurance)", scheme_type: "Crop Insurance", policy_level: "Central-State", budget_sanctioned_lakhs: 14200, amount_released_lakhs: 12780, amount_spent_lakhs: 11502, balance_unspent_lakhs: 1278, utilization_percent: 81.0, beneficiary_farmers: 56800, fund_source: "Central+State (50:50)", remarks: "Cotton+Orange coverage" },
    { district: "Nagpur", division: "Nagpur", year: 2018, scheme_name: "MIDH (Horticulture)", scheme_type: "Horticulture Dev", policy_level: "Central-State", budget_sanctioned_lakhs: 8200, amount_released_lakhs: 7380, amount_spent_lakhs: 6273, balance_unspent_lakhs: 1107, utilization_percent: 76.5, beneficiary_farmers: 32800, fund_source: "Central+State (60:40)", remarks: "Orange orchard development" },
    { district: "Nagpur", division: "Nagpur", year: 2019, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 12000, amount_released_lakhs: 12000, amount_spent_lakhs: 11280, balance_unspent_lakhs: 720, utilization_percent: 94.0, beneficiary_farmers: 80000, fund_source: "Central Government", remarks: "Full year" },
    { district: "Nagpur", division: "Nagpur", year: 2019, scheme_name: "MIDH (Horticulture)", scheme_type: "Horticulture Dev", policy_level: "Central-State", budget_sanctioned_lakhs: 8800, amount_released_lakhs: 7920, amount_spent_lakhs: 6732, balance_unspent_lakhs: 1188, utilization_percent: 76.5, beneficiary_farmers: 35200, fund_source: "Central+State (60:40)", remarks: "Nagpur orange brand support" },
    { district: "Nagpur", division: "Nagpur", year: 2020, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 13200, amount_released_lakhs: 13200, amount_spent_lakhs: 12408, balance_unspent_lakhs: 792, utilization_percent: 94.0, beneficiary_farmers: 88000, fund_source: "Central Government", remarks: "Covid year" },
    { district: "Nagpur", division: "Nagpur", year: 2020, scheme_name: "Covid Agri Relief Package", scheme_type: "Special Relief", policy_level: "Central-State", budget_sanctioned_lakhs: 9400, amount_released_lakhs: 9400, amount_spent_lakhs: 8836, balance_unspent_lakhs: 564, utilization_percent: 94.0, beneficiary_farmers: 75200, fund_source: "Central+State", remarks: "Lockdown relief" },
    { district: "Nagpur", division: "Nagpur", year: 2021, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 13800, amount_released_lakhs: 13800, amount_spent_lakhs: 13110, balance_unspent_lakhs: 690, utilization_percent: 95.0, beneficiary_farmers: 92000, fund_source: "Central Government", remarks: "DBT 3 instalments" },
    { district: "Nagpur", division: "Nagpur", year: 2021, scheme_name: "MIDH (Horticulture)", scheme_type: "Horticulture Dev", policy_level: "Central-State", budget_sanctioned_lakhs: 10200, amount_released_lakhs: 9180, amount_spent_lakhs: 7803, balance_unspent_lakhs: 1377, utilization_percent: 76.5, beneficiary_farmers: 40800, fund_source: "Central+State (60:40)", remarks: "Orange GI tag promotion" },
    { district: "Nagpur", division: "Nagpur", year: 2022, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 14400, amount_released_lakhs: 14400, amount_spent_lakhs: 13680, balance_unspent_lakhs: 720, utilization_percent: 95.0, beneficiary_farmers: 96000, fund_source: "Central Government", remarks: "3 instalments" },
    { district: "Nagpur", division: "Nagpur", year: 2022, scheme_name: "MIDH (Horticulture)", scheme_type: "Horticulture Dev", policy_level: "Central-State", budget_sanctioned_lakhs: 11000, amount_released_lakhs: 9900, amount_spent_lakhs: 8415, balance_unspent_lakhs: 1485, utilization_percent: 76.5, beneficiary_farmers: 44000, fund_source: "Central+State (60:40)", remarks: "Export promotion oranges" },
    { district: "Nagpur", division: "Nagpur", year: 2023, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 15000, amount_released_lakhs: 15000, amount_spent_lakhs: 14250, balance_unspent_lakhs: 750, utilization_percent: 95.0, beneficiary_farmers: 100000, fund_source: "Central Government", remarks: "Installment 13-15" },
    { district: "Nagpur", division: "Nagpur", year: 2023, scheme_name: "Namo Shetkari Mahasanman Nidhi", scheme_type: "Direct Income Support", policy_level: "State", budget_sanctioned_lakhs: 6000, amount_released_lakhs: 6000, amount_spent_lakhs: 5700, balance_unspent_lakhs: 300, utilization_percent: 95.0, beneficiary_farmers: 80000, fund_source: "State Government", remarks: "New state scheme 2023" },
    { district: "Nagpur", division: "Nagpur", year: 2023, scheme_name: "MIDH (Horticulture)", scheme_type: "Horticulture Dev", policy_level: "Central-State", budget_sanctioned_lakhs: 11800, amount_released_lakhs: 10620, amount_spent_lakhs: 9027, balance_unspent_lakhs: 1593, utilization_percent: 76.5, beneficiary_farmers: 47200, fund_source: "Central+State (60:40)", remarks: "Nagpur orange value chain" },
    { district: "Nagpur", division: "Nagpur", year: 2024, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 16200, amount_released_lakhs: 16200, amount_spent_lakhs: 15390, balance_unspent_lakhs: 810, utilization_percent: 95.0, beneficiary_farmers: 108000, fund_source: "Central Government", remarks: "Installment 16-18" },
    { district: "Nagpur", division: "Nagpur", year: 2024, scheme_name: "Namo Shetkari Mahasanman Nidhi", scheme_type: "Direct Income Support", policy_level: "State", budget_sanctioned_lakhs: 6480, amount_released_lakhs: 6480, amount_spent_lakhs: 6156, balance_unspent_lakhs: 324, utilization_percent: 95.0, beneficiary_farmers: 86400, fund_source: "State Government", remarks: "5th installment" },
    { district: "Nagpur", division: "Nagpur", year: 2024, scheme_name: "MIDH (Horticulture)", scheme_type: "Horticulture Dev", policy_level: "Central-State", budget_sanctioned_lakhs: 12600, amount_released_lakhs: 11340, amount_spent_lakhs: 9639, balance_unspent_lakhs: 1701, utilization_percent: 76.5, beneficiary_farmers: 50400, fund_source: "Central+State (60:40)", remarks: "MIDH 2024-25" },
    { district: "Nagpur", division: "Nagpur", year: 2025, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 17400, amount_released_lakhs: 17400, amount_spent_lakhs: 16530, balance_unspent_lakhs: 870, utilization_percent: 95.0, beneficiary_farmers: 116000, fund_source: "Central Government", remarks: "FY 2025-26" },
    { district: "Nagpur", division: "Nagpur", year: 2025, scheme_name: "Namo Shetkari Mahasanman Nidhi", scheme_type: "Direct Income Support", policy_level: "State", budget_sanctioned_lakhs: 6960, amount_released_lakhs: 6960, amount_spent_lakhs: 6612, balance_unspent_lakhs: 348, utilization_percent: 95.0, beneficiary_farmers: 92800, fund_source: "State Government", remarks: "Ongoing" },
    { district: "Nagpur", division: "Nagpur", year: 2025, scheme_name: "MIDH (Horticulture)", scheme_type: "Horticulture Dev", policy_level: "Central-State", budget_sanctioned_lakhs: 13400, amount_released_lakhs: 12060, amount_spent_lakhs: 10251, balance_unspent_lakhs: 1809, utilization_percent: 76.5, beneficiary_farmers: 53600, fund_source: "Central+State (60:40)", remarks: "Orange AI project linked" },

    // ── AURANGABAD ────────────────────────────────────────────
    { district: "Aurangabad", division: "Aurangabad", year: 2018, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 10400, amount_released_lakhs: 10400, amount_spent_lakhs: 9152, balance_unspent_lakhs: 1248, utilization_percent: 88.0, beneficiary_farmers: 69400, fund_source: "Central Government", remarks: "Scheme launch" },
    { district: "Aurangabad", division: "Aurangabad", year: 2018, scheme_name: "PMFBY (Crop Insurance)", scheme_type: "Crop Insurance", policy_level: "Central-State", budget_sanctioned_lakhs: 17200, amount_released_lakhs: 15480, amount_spent_lakhs: 13932, balance_unspent_lakhs: 1548, utilization_percent: 81.0, beneficiary_farmers: 68800, fund_source: "Central+State (50:50)", remarks: "Cotton+Soybean coverage" },
    { district: "Aurangabad", division: "Aurangabad", year: 2018, scheme_name: "State Agri Relief Fund", scheme_type: "Drought Relief", policy_level: "State", budget_sanctioned_lakhs: 9800, amount_released_lakhs: 9800, amount_spent_lakhs: 9212, balance_unspent_lakhs: 588, utilization_percent: 94.0, beneficiary_farmers: 78400, fund_source: "State Government", remarks: "Marathwada drought" },
    { district: "Aurangabad", division: "Aurangabad", year: 2019, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 13200, amount_released_lakhs: 13200, amount_spent_lakhs: 12408, balance_unspent_lakhs: 792, utilization_percent: 94.0, beneficiary_farmers: 88000, fund_source: "Central Government", remarks: "Full year" },
    { district: "Aurangabad", division: "Aurangabad", year: 2019, scheme_name: "State Agri Relief Fund", scheme_type: "Flood Relief", policy_level: "State", budget_sanctioned_lakhs: 12200, amount_released_lakhs: 12200, amount_spent_lakhs: 11346, balance_unspent_lakhs: 854, utilization_percent: 93.0, beneficiary_farmers: 97600, fund_source: "State Government", remarks: "2019 flood relief" },
    { district: "Aurangabad", division: "Aurangabad", year: 2020, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 14400, amount_released_lakhs: 14400, amount_spent_lakhs: 13536, balance_unspent_lakhs: 864, utilization_percent: 94.0, beneficiary_farmers: 96000, fund_source: "Central Government", remarks: "Covid year" },
    { district: "Aurangabad", division: "Aurangabad", year: 2020, scheme_name: "Covid Agri Relief Package", scheme_type: "Special Relief", policy_level: "Central-State", budget_sanctioned_lakhs: 12600, amount_released_lakhs: 12600, amount_spent_lakhs: 11844, balance_unspent_lakhs: 756, utilization_percent: 94.0, beneficiary_farmers: 100800, fund_source: "Central+State", remarks: "Covid relief Marathwada" },
    { district: "Aurangabad", division: "Aurangabad", year: 2021, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 15000, amount_released_lakhs: 15000, amount_spent_lakhs: 14250, balance_unspent_lakhs: 750, utilization_percent: 95.0, beneficiary_farmers: 100000, fund_source: "Central Government", remarks: "3 instalments DBT" },
    { district: "Aurangabad", division: "Aurangabad", year: 2021, scheme_name: "Nanaji Deshmukh Krishi Sanjivani", scheme_type: "Climate Resilience", policy_level: "State-World Bank", budget_sanctioned_lakhs: 11400, amount_released_lakhs: 10260, amount_spent_lakhs: 9126, balance_unspent_lakhs: 1134, utilization_percent: 80.0, beneficiary_farmers: 91200, fund_source: "State+World Bank", remarks: "Drought mitigation Marathwada" },
    { district: "Aurangabad", division: "Aurangabad", year: 2022, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 15600, amount_released_lakhs: 15600, amount_spent_lakhs: 14820, balance_unspent_lakhs: 780, utilization_percent: 95.0, beneficiary_farmers: 104000, fund_source: "Central Government", remarks: "3 instalments" },
    { district: "Aurangabad", division: "Aurangabad", year: 2023, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 16200, amount_released_lakhs: 16200, amount_spent_lakhs: 15390, balance_unspent_lakhs: 810, utilization_percent: 95.0, beneficiary_farmers: 108000, fund_source: "Central Government", remarks: "Installment 13-15" },
    { district: "Aurangabad", division: "Aurangabad", year: 2023, scheme_name: "Namo Shetkari Mahasanman Nidhi", scheme_type: "Direct Income Support", policy_level: "State", budget_sanctioned_lakhs: 6480, amount_released_lakhs: 6480, amount_spent_lakhs: 6156, balance_unspent_lakhs: 324, utilization_percent: 95.0, beneficiary_farmers: 86400, fund_source: "State Government", remarks: "New scheme 2023" },
    { district: "Aurangabad", division: "Aurangabad", year: 2023, scheme_name: "PMFBY (Crop Insurance)", scheme_type: "Crop Insurance", policy_level: "Central-State", budget_sanctioned_lakhs: 24800, amount_released_lakhs: 22320, amount_spent_lakhs: 20088, balance_unspent_lakhs: 2232, utilization_percent: 81.0, beneficiary_farmers: 99200, fund_source: "Central+State (50:50)", remarks: "Rs 2020 Cr state PMFBY" },
    { district: "Aurangabad", division: "Aurangabad", year: 2024, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 17400, amount_released_lakhs: 17400, amount_spent_lakhs: 16530, balance_unspent_lakhs: 870, utilization_percent: 95.0, beneficiary_farmers: 116000, fund_source: "Central Government", remarks: "Installment 16-18" },
    { district: "Aurangabad", division: "Aurangabad", year: 2024, scheme_name: "Namo Shetkari Mahasanman Nidhi", scheme_type: "Direct Income Support", policy_level: "State", budget_sanctioned_lakhs: 6960, amount_released_lakhs: 6960, amount_spent_lakhs: 6612, balance_unspent_lakhs: 348, utilization_percent: 95.0, beneficiary_farmers: 92800, fund_source: "State Government", remarks: "5th installment Oct 2024" },
    { district: "Aurangabad", division: "Aurangabad", year: 2025, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 18600, amount_released_lakhs: 18600, amount_spent_lakhs: 17670, balance_unspent_lakhs: 930, utilization_percent: 95.0, beneficiary_farmers: 124000, fund_source: "Central Government", remarks: "FY 2025-26" },
    { district: "Aurangabad", division: "Aurangabad", year: 2025, scheme_name: "Namo Shetkari Mahasanman Nidhi", scheme_type: "Direct Income Support", policy_level: "State", budget_sanctioned_lakhs: 7440, amount_released_lakhs: 7440, amount_spent_lakhs: 7068, balance_unspent_lakhs: 372, utilization_percent: 95.0, beneficiary_farmers: 99200, fund_source: "State Government", remarks: "Ongoing" },

    // ── LATUR ─────────────────────────────────────────────────
    { district: "Latur", division: "Aurangabad", year: 2018, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 14800, amount_released_lakhs: 14800, amount_spent_lakhs: 13024, balance_unspent_lakhs: 1776, utilization_percent: 88.0, beneficiary_farmers: 98800, fund_source: "Central Government", remarks: "Launch year" },
    { district: "Latur", division: "Aurangabad", year: 2018, scheme_name: "PMFBY (Crop Insurance)", scheme_type: "Crop Insurance", policy_level: "Central-State", budget_sanctioned_lakhs: 22400, amount_released_lakhs: 20160, amount_spent_lakhs: 18144, balance_unspent_lakhs: 2016, utilization_percent: 81.0, beneficiary_farmers: 89600, fund_source: "Central+State (50:50)", remarks: "Soybean+Tur coverage" },
    { district: "Latur", division: "Aurangabad", year: 2019, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 18000, amount_released_lakhs: 18000, amount_spent_lakhs: 16920, balance_unspent_lakhs: 1080, utilization_percent: 94.0, beneficiary_farmers: 120000, fund_source: "Central Government", remarks: "Full year" },
    { district: "Latur", division: "Aurangabad", year: 2020, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 19200, amount_released_lakhs: 19200, amount_spent_lakhs: 18048, balance_unspent_lakhs: 1152, utilization_percent: 94.0, beneficiary_farmers: 128000, fund_source: "Central Government", remarks: "Covid year" },
    { district: "Latur", division: "Aurangabad", year: 2020, scheme_name: "Covid Agri Relief Package", scheme_type: "Special Relief", policy_level: "Central-State", budget_sanctioned_lakhs: 16000, amount_released_lakhs: 16000, amount_spent_lakhs: 15040, balance_unspent_lakhs: 960, utilization_percent: 94.0, beneficiary_farmers: 128000, fund_source: "Central+State", remarks: "Covid relief Latur" },
    { district: "Latur", division: "Aurangabad", year: 2021, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 20400, amount_released_lakhs: 20400, amount_spent_lakhs: 19380, balance_unspent_lakhs: 1020, utilization_percent: 95.0, beneficiary_farmers: 136000, fund_source: "Central Government", remarks: "3 instalments" },
    { district: "Latur", division: "Aurangabad", year: 2021, scheme_name: "Nanaji Deshmukh Krishi Sanjivani", scheme_type: "Climate Resilience", policy_level: "State-World Bank", budget_sanctioned_lakhs: 13200, amount_released_lakhs: 11880, amount_spent_lakhs: 10567, balance_unspent_lakhs: 1313, utilization_percent: 80.0, beneficiary_farmers: 105600, fund_source: "State+World Bank", remarks: "Drought resilience Latur" },
    { district: "Latur", division: "Aurangabad", year: 2022, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 21600, amount_released_lakhs: 21600, amount_spent_lakhs: 20520, balance_unspent_lakhs: 1080, utilization_percent: 95.0, beneficiary_farmers: 144000, fund_source: "Central Government", remarks: "3 instalments" },
    { district: "Latur", division: "Aurangabad", year: 2023, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 22800, amount_released_lakhs: 22800, amount_spent_lakhs: 21660, balance_unspent_lakhs: 1140, utilization_percent: 95.0, beneficiary_farmers: 152000, fund_source: "Central Government", remarks: "Installment 13-15" },
    { district: "Latur", division: "Aurangabad", year: 2023, scheme_name: "Namo Shetkari Mahasanman Nidhi", scheme_type: "Direct Income Support", policy_level: "State", budget_sanctioned_lakhs: 9120, amount_released_lakhs: 9120, amount_spent_lakhs: 8664, balance_unspent_lakhs: 456, utilization_percent: 95.0, beneficiary_farmers: 121600, fund_source: "State Government", remarks: "New scheme 2023" },
    { district: "Latur", division: "Aurangabad", year: 2024, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 24000, amount_released_lakhs: 24000, amount_spent_lakhs: 22800, balance_unspent_lakhs: 1200, utilization_percent: 95.0, beneficiary_farmers: 160000, fund_source: "Central Government", remarks: "Installment 16-18" },
    { district: "Latur", division: "Aurangabad", year: 2024, scheme_name: "Namo Shetkari Mahasanman Nidhi", scheme_type: "Direct Income Support", policy_level: "State", budget_sanctioned_lakhs: 9600, amount_released_lakhs: 9600, amount_spent_lakhs: 9120, balance_unspent_lakhs: 480, utilization_percent: 95.0, beneficiary_farmers: 128000, fund_source: "State Government", remarks: "5th installment" },
    { district: "Latur", division: "Aurangabad", year: 2025, scheme_name: "PM-KISAN", scheme_type: "Direct Income Support", policy_level: "Central", budget_sanctioned_lakhs: 25200, amount_released_lakhs: 25200, amount_spent_lakhs: 23940, balance_unspent_lakhs: 1260, utilization_percent: 95.0, beneficiary_farmers: 168000, fund_source: "Central Government", remarks: "FY 2025-26" },
    { district: "Latur", division: "Aurangabad", year: 2025, scheme_name: "Namo Shetkari Mahasanman Nidhi", scheme_type: "Direct Income Support", policy_level: "State", budget_sanctioned_lakhs: 10080, amount_released_lakhs: 10080, amount_spent_lakhs: 9576, balance_unspent_lakhs: 504, utilization_percent: 95.0, beneficiary_farmers: 134400, fund_source: "State Government", remarks: "Ongoing" },
];

// ============================================================
//  SEED FUNCTIONS
// ============================================================

async function seedCollection(collectionName, data, labelField) {
    console.log(`\n📦 Seeding collection: "${collectionName}" (${data.length} records)...`);
    const collectionRef = db.collection(collectionName);
    const batchSize = 400;
    let count = 0;

    for (let i = 0; i < data.length; i += batchSize) {
        const batch = db.batch();
        const chunk = data.slice(i, i + batchSize);

        chunk.forEach((record) => {
            const docRef = collectionRef.doc(); // auto-generated ID
            batch.set(docRef, {
                ...record,
                created_at: admin.firestore.FieldValue.serverTimestamp(),
            });
        });

        await batch.commit();
        count += chunk.length;
        console.log(`   ✅ Committed ${count}/${data.length} records`);
    }

    console.log(`✔  Done seeding "${collectionName}"`);
}

async function main() {
    console.log("🚀 Starting Firebase Firestore Seeder...");
    console.log("   Project: Maharashtra Agriculture Data (2018–2025)");
    console.log("   Divisions: Amravati | Nagpur | Aurangabad\n");

    try {
        await seedCollection("maharashtra_agriculture", agricultureData, "crop");
        await seedCollection("maharashtra_agri_finance", financeData, "scheme_name");

        console.log("\n🎉 All data seeded successfully!");
        console.log("\n📊 Collections created in Firestore:");
        console.log("   • maharashtra_agriculture  →  Crop production & budget data");
        console.log("   • maharashtra_agri_finance →  Government scheme finance data");
        console.log("\n💡 Tip: You can now query by district, year, division, or scheme_name");

    } catch (error) {
        console.error("❌ Error seeding data:", error);
        process.exit(1);
    } finally {
        process.exit(0);
    }
}

main();
